### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by QOAL** [QOAL/GymBadge#3]
As this tool is used by many people from all around the world, it would be nice to provide translations like Pokémon Go does.

Plurals seem to be the only thing stopping this from being a simple array job from a programming perspective, unless we can get away that, otherwise I'm sure there are a couple of nice small size l10n libraries that can be used.

Volunteers are also needed to help translate the strings.

**Comment by yuzuri** [comment]
Hi.
Thank you for developing the nice tool. We Japanese are using your tool via web browser.

> Volunteers are also needed to help translate the strings.
I can help you in terms of translating the English word into the Japanese word.
I scanned through "index.html". How do you translate the English text into each own language now?

yuzu

**Comment by yuzuri** [comment]
Hi.
Thank you for developing the nice tool. We Japanese are using your tool via web browser.

> Volunteers are also needed to help translate the strings.

I can help you in terms of translating the English word into the Japanese word.
I scanned through "index.html". How do you translate the English text into each own language now?

yuzu

**Comment by QOAL** [comment]
Hi Yuzu,
Thank you for taking the time to respond to this.

Support for translations hasn't been added yet. (You're the first to take interest)

I've been working on adding translation support to the code today, and it should be ready sometime tomorrow. (London/GMT)

**Comment by yuzuri** [comment]
Hi Scott,

Thank you for quick response.

> Support for translations hasn't been added yet. (You're the first to take interest)
> I've been working on adding translation support to the code today, and it should be ready sometime tomorrow.

I see.
I will wait for the new code.  :D

**Comment by QOAL** [comment]
I have translations working locally now (no right-to-left text support yet), I still need to back port some of the translation code to the open source version. So I'm sorry that I have nothing for you to test a translation with today.

Anyway, here's the current language file: https://github.com/QOAL/GymBadge/blob/i18n/strings.js

It just needs to be extended with additional languages.
Copy everything from the `"en": {` down to `},` and translate the string on the right hand side of each line.

The `%{word}`'s should not be translated, they automatically get replaced by the app.

The translation library being used is called polyglot.js (http://airbnb.io/polyglot.js/polyglot.html)

It's late and I need to sleep, I'll provide a working index.html tomorrow. Feel free to wait until then before translating.

**Comment by yuzuri** [comment]
Dear Scott,

I appreciate the continuous update. 

> It just needs to be extended with additional languages.
> Copy everything from the "en": { down to }, and translate the string on the right hand side of each line.
> The %{word}'s should not be translated, they automatically get replaced by the app.

I see how to add the Japanese text. 

> I'll provide a working index.html tomorrow. Feel free to wait until then before translating.

This means there is no work which I address now?
Anyway, I think there is no reason to hurry. Please relax and continue the lazy development of the code :D
As you know, Groudon is appearing for a limited time only. You should miss the strong Groudon!

**Comment by QOAL** [comment]
The live website now supports translations, and I have updated the github version to support translations too: https://github.com/QOAL/GymBadge/tree/i18n/

The strings file (https://github.com/QOAL/GymBadge/blob/i18n/strings.js) works with both, but the website has more features so you may want to save the website and test with that.

Please let me know if you have any question or issues.

**Comment by yuzuri** [comment]
Hi,

After "git clone" and "git checkout", I found your update. But, via "index.html", I could not measure the the level of gym badge.
Are you assuming access from a mobile phone (such as iPhone or android) instead of the the computer?

Could you tell me the url of the official web site?
I usually watch https://raidbadge.neocities.org/ . However, this web site looks not official web cite which you open.

yuzu

**Comment by QOAL** [comment]
The official url is https://qplanner.co.uk/tmp/pkmngo/

---- yuzuri wrote ----


Hi,

After "git clone" and "git checkout", I found your update. But, via "index.html", I could not measure the the level of gym badge.
Are you assuming access from a mobile phone (such as iPhone or android) instead of the the computer?

Could you tell me the url of the official web site?
I usually watch https://raidbadge.neocities.org/ . However, this web site looks not official web cite which you open.

yuzu

**Comment by QOAL** [comment]
https://qplanner.co.uk/tmp/translate/
